import {
  BarChart3,
  ClipboardList,
  DollarSign,
  Users,
  GraduationCap,
  FileEdit,
  Folder,
  TrendingUp,
  Calendar,
  FileText,
  Sparkles,
  Crown,
  User,
  Handshake,
  Building2,
  MapPin,
  CheckCircle2,
  Clock,
  AlertCircle,
  Plus,
  Search,
  Settings,
  Bell,
  LogOut,
  ChevronRight,
  ChevronLeft,
  X,
  Eye,
  Edit,
  Trash2,
  Download,
  Upload,
  Filter,
  MoreVertical,
  Mail,
  Lock,
  Key,
  Unlock,
  TrendingUp as ArrowUp,
  AlertTriangle,
  Clock as Timer,
  Star,
  Info,
  Target,
  ScrollText,
  UserCircle,
  TrendingDown,
  Receipt,
  Wallet,
  Briefcase,
  Package,
  FileSpreadsheet,
  Check,
  UserPlus,
  RefreshCw,
  Lightbulb,
  Phone,
  History,
  Minus,
  Archive,
  Pin,
  ChevronUp,
  ChevronDown,
  CheckSquare,
  ArrowUpDown,
  LayoutGrid,
  Table,
  Save,
  List,
  Link,
  CheckCheck,
  CalendarX,
  BellOff,
  Circle,
  PieChart,
  Award,
  CreditCard,
  Loader,
  EyeOff,
  ArrowLeft,
  HelpCircle,
  CheckCircle,
  UserCheck,
  BookOpen,
  CalendarDays,
  Bookmark,
  ChevronDown as ChevronDownIcon
} from 'lucide-react'

// Mapping des emojis vers les icônes lucide-react
const ICON_MAP = {
  '📊': BarChart3,
  '📋': ClipboardList,
  '💰': DollarSign,
  '👥': Users,
  '🎓': GraduationCap,
  '📝': FileEdit,
  '📁': Folder,
  '📈': TrendingUp,
  '📅': Calendar,
  '📄': FileText,
  '🆕': Sparkles,
  '👑': Crown,
  '👤': User,
  '🤝': Handshake,
  '🏢': Building2,
  '📍': MapPin,
  '✓': CheckCircle2,
  '⏳': Clock,
  '⚠️': AlertCircle,
  '➕': Plus,
  '🔍': Search,
  '⚙️': Settings,
  '🔔': Bell,
  '🚪': LogOut,
  '→': ChevronRight,
  '←': ChevronLeft,
  '×': X,
  '👁️': Eye,
  '✏️': Edit,
  '🗑️': Trash2,
  '⬇️': Download,
  '⬆️': Upload,
  '🔽': Filter,
  '⋮': MoreVertical,
  '📧': Mail,
  '🔒': Lock,
  '🔑': Key,
  '🔓': Unlock,
  '↑': ArrowUp,
  '⚠': AlertTriangle,
  '⏱️': Timer,
  '⭐': Star,
  '○': CheckCircle2,
  '✅': CheckCircle2,
  '❌': X,
  '📌': MapPin,
  'ℹ️': Info,
  '🎯': Target,
  '📜': ScrollText,
  '👨‍🏫': UserCircle,
  '💵': DollarSign,
  '💸': TrendingDown,
  '💼': Briefcase,
  '📦': Package,
  '📚': BookOpen,
  '🗓️': CalendarDays,
  '▼': ChevronDownIcon
}

// Mapping direct par nom d'icône (pour usage sans emoji)
const NAMED_ICONS = {
  BarChart3,
  ClipboardList,
  DollarSign,
  Users,
  GraduationCap,
  FileEdit,
  Folder,
  TrendingUp,
  Calendar,
  FileText,
  Sparkles,
  Crown,
  User,
  Handshake,
  Building2,
  MapPin,
  CheckCircle2,
  Clock,
  AlertCircle,
  Plus,
  Search,
  Settings,
  Bell,
  LogOut,
  ChevronRight,
  ChevronLeft,
  X,
  Eye,
  Edit,
  Trash2,
  Download,
  Upload,
  Filter,
  MoreVertical,
  Mail,
  Lock,
  Key,
  Unlock,
  ArrowUp,
  AlertTriangle,
  Timer,
  Star,
  Info,
  Target,
  ScrollText,
  UserCircle,
  TrendingDown,
  Receipt,
  Wallet,
  Briefcase,
  Package,
  FileSpreadsheet,
  Check,
  UserPlus,
  RefreshCw,
  Lightbulb,
  Phone,
  History,
  Minus,
  Archive,
  Pin,
  ChevronUp,
  ChevronDown,
  CheckSquare,
  ArrowUpDown,
  LayoutGrid,
  Table,
  Save,
  List,
  Link,
  CheckCircle: CheckCircle2,
  XCircle: X,
  CheckCheck,
  CalendarX,
  BellOff,
  Circle,
  PieChart,
  Award,
  CreditCard,
  Loader,
  EyeOff,
  ArrowLeft,
  HelpCircle,
  UserCheck,
  BookOpen,
  Bookmark
}

/**
 * Composant Icon centralisé pour remplacer les emojis
 * @param {string} name - Nom de l'icône (lucide-react) ou emoji
 * @param {number|string} size - Taille de l'icône (défaut: 20)
 * @param {string} color - Couleur de l'icône (défaut: currentColor)
 * @param {string} className - Classes CSS additionnelles
 * @param {object} props - Autres props à passer à l'icône
 */
export default function Icon({ name, size = 20, color = 'currentColor', className = '', ...props }) {
  // Si c'est un emoji, utiliser le mapping
  if (ICON_MAP[name]) {
    const IconComponent = ICON_MAP[name]
    return (
      <IconComponent
        size={size}
        color={color}
        className={className}
        {...props}
      />
    )
  }

  // Si c'est un nom d'icône direct
  if (NAMED_ICONS[name]) {
    const IconComponent = NAMED_ICONS[name]
    return (
      <IconComponent
        size={size}
        color={color}
        className={className}
        {...props}
      />
    )
  }

  // Fallback : retourner l'emoji original si non trouvé
  console.warn(`Icon "${name}" not found in mapping`)
  return <span style={{ fontSize: size }}>{name}</span>
}

// Export des icônes nommées pour usage direct
export {
  BarChart3,
  ClipboardList,
  DollarSign,
  Users,
  GraduationCap,
  FileEdit,
  Folder,
  TrendingUp,
  Calendar,
  FileText,
  Sparkles,
  Crown,
  User,
  Handshake,
  Building2,
  MapPin,
  CheckCircle2,
  Clock,
  AlertCircle,
  Plus,
  Search,
  Settings,
  Bell,
  LogOut,
  ChevronRight,
  ChevronLeft,
  X,
  Eye,
  Edit,
  Trash2,
  Download,
  Upload,
  Filter,
  MoreVertical,
  Mail,
  Lock,
  Key,
  Unlock,
  ArrowUp,
  AlertTriangle,
  Timer,
  Star,
  Info,
  Target,
  ScrollText,
  UserCircle,
  TrendingDown,
  Receipt,
  Wallet,
  Briefcase,
  Package,
  FileSpreadsheet,
  Check,
  UserPlus,
  UserCheck,
  RefreshCw,
  Lightbulb,
  Phone,
  History,
  Minus,
  Archive,
  Pin,
  ChevronUp,
  ChevronDown,
  CheckSquare,
  ArrowUpDown,
  LayoutGrid,
  Table,
  Save,
  List,
  CheckCheck,
  CalendarX,
  BellOff,
  Circle,
  PieChart,
  Award,
  CreditCard,
  Loader,
  EyeOff,
  ArrowLeft,
  HelpCircle,
  CheckCircle,
  Bookmark
}

